/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/generate": {
    /** Generate Python code */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["GenerateRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["GenerateResponse"];
          };
        };
      };
    };
  };
  "/api/exec-code": {
    /** Execute Python code */
    post: {
      requestBody?: {
        content: {
          "application/json": components["schemas"]["ExecCodeRequest"];
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["ExecCodeResponse"];
          };
        };
      };
    };
  };
  "/api/upload-file": {
    /** Upload file */
    post: {
      requestBody?: {
        content: {
          "multipart/form-data": {
            /** Format: binary */
            file?: string;
          };
        };
      };
      responses: {
        /** @description OK */
        200: {
          content: {
            "application/json": components["schemas"]["UploadFileResponse"];
          };
        };
      };
    };
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    GenerateRequest: {
      /** @description User input */
      user_input?: string;
    };
    GenerateResponse: {
      /** @description Generated code */
      generated_code?: string;
    };
    /**
     * @example {
     *   "code": "import os\na = 10\na\n"
     * }
     */
    ExecCodeRequest: {
      /** @description Python code */
      code?: string;
    };
    ExecCodeResponse: {
      /** @description Output of the code */
      output?: string;
      /** @description Type of the message */
      message_type?: string;
    };
    UploadFileResponse: {
      /** @description Uploaded file name */
      file_name?: string;
      /** @description Uploaded file URL */
      blob_url?: string;
      /** @description Financial data */
      financial_data?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type external = Record<string, never>;

export type operations = Record<string, never>;
